INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (3, 3, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (4, 4, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (5, 5, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (6, 6, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (7, 7, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (8, 8, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (9, 9, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (10, 10, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (11, 11, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (12, 12, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (13, 13, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (14, 14, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0);
INSERT INTO Droits (id_droit, id_personnel, peut_gerer_animaux, peut_gerer_soins, peut_gerer_alimentation, peut_gerer_enclos, peut_gerer_personnel, peut_gerer_boutiques, peut_gerer_parrainages, peut_consulter_ca, peut_gerer_reparations, est_admin) VALUES (15, 15, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0);

COMMIT;
