services:
  oracle-db:
    image: gvenzl/oracle-free:slim-faststart
    container_name: oracle-free-db
    restart: unless-stopped
    ports:
      - "1521:1521"
      - "5500:5500"    
    environment:
      ORACLE_PASSWORD: MdPoracleflo83!  
      ORACLE_DATABASE: FREEPDB1   
    volumes:
      - oracle-data:/opt/oracle/oradata 

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zoo-web
    restart: unless-stopped
    ports:
      - "8000:80" 
    volumes:
      - ./web:/var/www/html 

volumes:
  oracle-data:
    driver: local
